title: Shubham Sharma # your name (or website title) here
logo: "/images/shubham-linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Marketing Coordinator @ Direct Objective Consulting 
  <br><br>
  <a href="https://www.linkedin.com/in/shubham-sharma-4bb00638/">View My LinkedIn Profile</a> 
